### ISSUE TITLE
Game Development Checklist

### ISSUE THREAD

**Issue by lock9** [CityOfZion/props#1]
This is a game development checklist. This is an epic that will track all issues needed to finish the MVP

Important tasks:
- [ ] #2 

Concept (GDD):
- [x] #6
- [x] #7
- [x] #8
- [x] #5
- [x] #9
- [ ]  Describe other player interactions
- [ ]  Combat simulation (x2)
- [ ]  Game metrics

Art Design:

- [ ] #11
- [ ]  Game HUD
- [ ]  Game Menu
- [ ]  Sketches
- [ ]  Combat Arena
- [ ]  Landing Page
- [ ]  Backgrounds
- [ ]  Background Music 
- [ ]  How to Play
- [ ]  Help
- [ ]  404 Page

UI Development:

- [ ] HUD implementation
- [ ]  Smart contract integration
- [ ]  Combat simulation
- [ ]  Wallet integration

Smart Contract Development:

- [ ] Governance Smart Contract
- [ ] Game Mechanics Smart Contract
- [ ] Game Token Smart Contract
