### ISSUE TITLE
Create game art design briefing

### ISSUE THREAD

**Issue by lock9** [CityOfZion/props#2]
We need to quote multiple studios and artists to know how much this will cost us. We need to write a briefing to send to the artists.

The briefing must include:

- [ ]  Game summary
- [ ]  #7 
- [ ]  Assets to be designed 
- [ ]  Backgrounds (character, arena)
- [x] #10
- [ ]  List of deliverables and their format
- [ ]  Ensure that this acquisition will allow us to resell the art as an NFT
